# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Focus's wiki
email: wwwicbd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  好记性不如烂笔头,站在岸上学不会游泳
baseurl: "/wiki" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: CbdFocus
github_username:  icbd

# Build settings
markdown: kramdown
